<<<<<<< HEAD
=======
"use client"
>>>>>>> b670095fad2fed299bed38d9073f3af43e8bda4d
import "./globals.css";
if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap");
}
import "../style/index.scss";
import AppProvider from "@/contextApi/AppProvider";
<<<<<<< HEAD
import { Toaster } from "sonner";
=======
import { ToastContainer } from "react-toastify";

>>>>>>> b670095fad2fed299bed38d9073f3af43e8bda4d

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.ico" />
        </head>

        <body suppressHydrationWarning={true}>
          <AppProvider>
            {children}
<<<<<<< HEAD
            <Toaster  position="top-center" richColors />
=======
            <ToastContainer
              position="top-left"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
>>>>>>> b670095fad2fed299bed38d9073f3af43e8bda4d
          </AppProvider>
        </body>
      </html>
    </>
  );
}
